Use ament_clang_format
nobleo/full_coverage_path_planner pull request #45
Opened 2023-06-08 11:17 UTC by Timple

2023-06-08 11:51 UTC, rokusottervanger approved these changes

2023-06-08 12:14 UTC, Rayman requested changes
We don't use this repo anymore

2023-06-09 07:45 UTC, rokusottervanger commented
> We don't use this repo anymore

Yes we do. It's in both the ROS and the ROS 2 targets for the full coverage path planner. I think you might be confusing this with the path tracking PID.

2023-06-12 07:12 UTC, Rayman approved these changes

2023-06-12 07:15 UTC, merged